- README.md
`한 줄 소감을 쓰시오`
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
이 문제는...
- 몇 분?
1. 이 문제는...
이 문제의 포인트는...
> [220728] 윤태준

- syj/220804/BOJ_12904_A와B.java
- syj/220804/BOJ_1759_암호만들기.java
- syj/220804/BOJ_1790_수이어쓰기2.java
- syj/220804/BOJ_2800_괄호제거.java
- syj/220804/BOJ_3019_테트리스.java
`수 이어 쓰기 2 ... 잊지 않겠어`
* 메모리 : 70100 kb
* 실행시간 : 332 ms
- 괄호를 제거하기 위해서 괄호 짝의 인덱스를 알아야 한다.
- 괄호를 제거하는 경우의 수를 1~n개 까지 전부 구해야 한다. -> 부분집합
- 겹괄호가 있을 때 괄호를 제거한 결과에서 중복이 있을 수 있다
- 약 1시간
1. ArrayList에 수식 저장
2. 스택을 이용해 괄호 쌍 인덱스 map에 저장  -> key값은 따로 배열에 저장
map - { 0 : 6, 3 : 5, ... }
arr - [0, 3, ...]
3. 부분집합으로 삭제 - 1~n -> 중복체크 (겹괄호가 있을 경우 중복이 생김)
4. 사전 순으로 정렬 후 출력
부분집합 사용
중복체크
_!!! 해시트리셋 사용하면 중복체크, 정렬 생략 가능 !!!_
* 메모리 : 12868 kb	
* 실행시간 : 112 ms
- 문제대로 수를 쭉 나열해서 인덱스를 뽑아오면 메모리초과, 시간초과가 날 것이 분명한 문제 ..
- 규칙을 찾아야 한다
- 2일
1 자리 : 1 ~ 9 		(1 - 9개) + 9개
2 자리 : 10 ~ 99 		(10 - 189개) + 180개
3 자리 : 100 ~ 999		(190 - 2889개) + 2700개
4 자리 : 1000 ~ 9999	(2900 - 38889개) + 3600개
위 규칙을 활용해서 
1. k가 포함된 자리 수를 찾은 뒤
- 자리 수마다 9 * i * Math.pow(10, i - 1) 개씩 늘어난다는 점을 활용해 k의 자리 수 구하기
2. 몫과 나머지를 이용해 k가 위치하는 수와 
- k에서 이전 자리 …
> [ 220804 ] 서예지

- ahg/220804/AandB.java
- ahg/220804/NumberContinuation2.java
- ahg/220804/RemoveBracket.java
- ahg/220804/Tetris.java
생각을 많이해야하는 문제들이 있었다
- 맞는 괄호 쌍의 인덱스를 같이 저장
- 부분집합을 사용해야 하는 문제
- 2시간
1. 괄호 쌍을 저장할 객체와 그 객체를 담을 리스트 선언
2. 스택을 이용해 괄호 쌍의 인덱스번호를 담은 객체를 리스트에 추가
3. 리스트를 기준으로 탐색
- 알맞는 괄호 쌍을 체크 하는것
- 순열,조합,부분탐색을 할 때 여러개의 인덱스를 한번에 관리하는 방법
- 주어진 범위가 너무 커 완전탐색을 이용한 풀이는 불가능
- 자릿수 규칙을 알아야 풀 수 있는 문제
풀지못함
1 ~ 9 까지는 1자리 9개
10 ~ 99까지는 2자리 90
100 ~ 999 까지는 3자리 900
1000 ~ 9999 4자리 9000
10000 ~ 99999 5자리 90000
100000 ~ 999999 6자리 900000
1000000 ~ 9999999 7자리 ...
10000000 ~ 99999999 8자리 ... 고정적으로 증가
1. 위  규칙에 의거해서 k의 값이 각 자릿수가 가지고 있는 숫자보다 클 경우 숫자의 갯수만큼 뺴주면서 k번째가 존재하는 자릿수 찾기
2. 자릿수를 찾았으면 나누기 연산과 모듈러 연산을 통해 k가 존재하는 숫자와 그 숫자 안에 k가 몇번째인지 찾은 후 출력
- 자릿수마다 가진 숫자가 몇개인지 규칙을 찾는것
- 자릿수의 숫자만큼 더하면서 k값과 비교했을 경우 예외가 발생할 가능성이 매우 크니 k에서 자릿수 값만큼 빼주면서 계산할것
- 알고리즘이 들어가지 않은 구현 문제
- 블럭마다 놓을 수 있는 규칙이 존재
40분
일단 각 블럭마다 블럭을 놓을 수 있는 모든 경우의 수를 구하기
1번 …
> [220804] 안효관

- jes/220802/Solution_G5_17609_회문.java
- yhg/220804/BOJ_12904.java
- yhg/220804/BOJ_1759.java
- yhg/220804/BOJ_1790.java
- yhg/220804/BOJ_2800.java
- yhg/220804/BOJ_3019.java
`한 줄 소감을 쓰시오`
문제를 제대로 읽고 출력 조건을 미리 설정하자
이 문제는 모든 괄호에 대한 정보를 저장해서 괄호의 부분집합을 만들어서 해당 인덱스의 괄호를 지워가면서 수식을 만들어 내야 하는 순조부 문제다.
- 40분
1. 여는 괄호를 만날때마다 해당 인덱스를 deque에 넣는다.
2. 만약 닫는괄호를 만나면 완성된 괄호를 하나 만들 수 있다. 
3. 해당 인덱스를 [여는괄호 인덱스 , 닫는괄호 인덱스] 의 형식으로 넣는다.
4. 끝까지 완료가 되면 추가한 인덱스 배열의 부분집합을 구한다.
5. 해당 부분집합에 해당하는 인덱스의 괄호를 지우고 문자열로 전환한다. 
6. 만약 이미 만들 문자열이 있다면 해당 문자열은 결과에 추가하지 않고 없었다면 추가한다. 
7. 결과 리스트를 오름차순으로 정렬하고 출럭한다.
괄호에 대한 정보를 정확하게 리스트에 저장해야하고 저장한 수식의 중복이 있는지 꼭 확인해야 한다. 
이 문제는 각 자리별 개수의 규칙을 찾아내야한다. 
각 문자열의 길이를 기준으로 내가 찾으려는 자리가 몇자리인지 알아야 하고 몇자리인지 알았다면 출력해야 하는 숫자가 몇번쨰 숫자인가를 체크해서 출력한다.
- 1시간 반 + 출력제어 안해줘서 미뤄둔 시간 3일 
1. 각 자리별 개수를 저장한다.
- 1자리 : 9개
- 2자리 : 180개
- 3자리 : 2700개
2. 각자리수는 9 * 자리수 * 10의 자리수제곱 이다. 
3. 후에 입력받은 k에서 이전자리수의 개수를 뺀다. 
4. 남은 수는 해당 자리수에서 몇번째 자리인가를 나타낸다.
5. 남은 자리수의 개수를 자리수로 나눠주면 몇번째 숫자인지 …
> [220804] 유현근

- jes/220804/Main_G5_12904_A와B.java
- jes/220804/Main_G5_1759_암호만들기.java
- jes/220804/Main_G5_1790_수이어쓰기2.java
- jes/220804/Main_G5_2800_괄호제거.java
- jes/220804/Main_S1_3019_테트리스.java
`문제 꼼꼼하게 읽기! 다음주도 화이팅 ^____^`
괄호 쌍을 제거해서 나올 수 있는 서로 다른 식을 사전 순으로 출력하는 것이 목표
-> 괄호 쌍을 제거하는 거니까 괄호 쌍만 가지고 할 수 있지 않을까 생각
- 2시간
1. 부분 집합 알고리즘 사용
2. Index 클래스에 괄호와 괄호의 위치를 담아 스택(st)에 Index형으로 들어가게 함
3. 스택으로 괄호 쌍을 찾고 조건문을 통해 리스트(par)에 괄호 쌍 각각의 위치를 Point 클래스(int, int 담아주는 클래스) 통해 담아줌
4. 괄호 쌍의 부분집합을 구하고 임시 문자열에 체크된(true) 괄호 쌍을 제거한 문자열을 TreeSet에 담아 사전순으로 정렬
- 괄호 쌍 찾고 괄호가 제거되는 경우의 수 모두 구하기!
1~ 9 9개
10~ 99 90개
100~ 999 900개
...
위와 같은 규칙을 통해 K번째 수가 있는 숫자를 구한 다음 K를 구하는 것을 목표
- 3시간
1. K번째 수가 어떤 숫자에 속해있는지 찾기 위해 while문으로 반복하여 자릿수를 하나씩 늘려가며 자릿수별 숫자 개수를 곱한 것을 빼줌
2. 반복문을 빠져나왔을 때 K번째 수가 포함된 숫자의 자릿수, 그 자릿수의 첫번째 수(1, 10, 100, ...)에서 몇개의 숫자를 건너뛰어야 하는지((tmp-1)/length) 도출
3. 현재 자릿수의 첫번째 수(num) 에서 건너뛴 숫자를 구하고, 구한 숫자에서 최종적으로 K를 구함
- int형 변수에 담은 수들이 for문을 돌면서 int 타입 범위(-2147483648 ~ 2147483647)를 벗어나 처리 불가
- 해결 → …
> [220804] 조은서

- ytj/220811/BOJ_14891_Gear.java
- ytj/220811/BOJ_17070_MovePipe01.java
` 어려워진다고 핑계 되지 않고 더더욱 분발하도록 하겠습니다. `
파이프를 특정 조건에 따라 이동 시켜 파이프의 끝이 NXN 배열 마지막 인덱스에 도달 할 수 있는 모든 경우의 수를 구하는 것이다. 파이프의 이동 특징을 파악하고, 파이프의 상태에 따라 조건이 어떻게 달라지는지, 
달라진 조건을 어떻게 구현할지 파악하는 것이 가장 중요하다. 
- 1h 20m
1. 파이프의 상태에 따른 조건 파악 ( 가로, 대각선, 세로 )
2. 이동 할 수 있는 조건에 따른 경우의 수를 ( DFS )재귀를 통해 구현한다.
파이프의 각 상태에 따른 조건을 정확하게 하여 실수하지 않도록 해야한다.
어느 한 톱니바퀴를 시계방향, 반시계방향으로 한칸 회전 시켰을 때, 양 옆에 위치한 톱니바퀴 또한 조건에 따라 영향을 받게 되어 있다. 이를 바탕으로 입력 값에 따라  12시 방향의 톱니의 상태에 따라 해당되는 결과를 도출한다.
- 2h 30m 
>  결국 틀림
1. 첫번째, 두번째, 세번째, 네번째 톱니 중 먼저 움직이는 톱니에 따라 영향을 받는 톱니가 달라지므로 각 경우를 나눈다.
2. 톱니가 움직인 후, 정보를 갱신할 수 있도록 알맞는 자료구조에 정보를 담는다.
3. 조건에 따라 톱니를 움직이며 톱니 정보들을 갱신한다.
4. 톱니의 움직임이 모두 끝난 후, 12시 위치의 톱니 값들을 확인하여 결과를 도출 한다.
조건을 설정하는 것은 어렵지 않지만, 갱신되는 톱니바퀴의 정보들을 어떤 자료구조에 담고 내용들을 갱신할지가 매우 중요하다.
> [220811] 윤태준

- yhg/220818/BOJ_1342_행운의 문자열.java
- yhg/220818/SWEA_1227_미로2.java
- yhg/220818/SWEA_2117_홍방범서비스.java
- yhg/220818/SWEA_2819_격자판붙이기.java
- yhg/220818/SWEA_5653_줄기세포배양.java
` 이번주는 그래도 좀 괜찮게 했다???
BFS , 구현 
세포의 배양 조건과 결과를 체크하는 조건을 잘 생각해서 풀어야 한다. 
3시간 30분
1.  배양할 세포의 class를 만든다.
2. 세포를 입력받고 이에 대한 정보를 저장한다.
3. 세포배열의 복사본을 만들어서 배양시에 사용한다.
4. 원본의 세포배열을 탐색하면서 분열할 수 있는지 확인한다.
5. 만약 분열할 수 있다면 복사본에 해당 세포자리에 분열을 시도한다. 
6. 만약 방금 만들어진 세포자리면 생명력 비교후에 분열한다.
7. 아니라면 넘어간다.
8. 분열이 전부 끝나면 생명주기에 안에 있는 세포를 세준다.
생명주기 확인 , 시간초과 주의하기
순열
현재 구성하고 있는  문자에 대한 정보를 잘 정리하는것이 포인트
30분
1. 입력받은 알파벳만으로 구성된 map을 작성하면서 개수 세기
2. 문자열을 하나씩 돌면서 붙이는데 이전과 다를때만 붙이고 사용한 개수를 체크한다.
3. 문자열마다 사용한 visited다르기때문에 복사본을 넘기면서 조합
4. 전부다 성공적으로 사용했으면 결과 +1
visited 복사본을 가지고 다니는것이 필요했다. 
BFS
미로를 탐색하자
30분
1. 시작위치부터 4방탐색
2. 0이면 dq에 추가하고 아니면 지나감
3. 3을 만나면 종료 dq가 다 비었는데 3 못만나면 실패
4방탐색
BFS
30분
1. 4방탐색하면서 숫자를 이어 붙임
2. 7자리 글자 완성되면 set에 추가하면서 중복 제거
3. set의 size 출력
4방탐색을 잘하자
완전탐색
1시간
1. 서비스의 범위를 전체 탐색할 수 있을 때까지 범위를 넓히면서 탐색
2. …
> [220818] 유현근

- jes/220818/Main_S1_1342_행운의문자열.java
- jes/220818/Solution_2117_홈방법서비스.java
- jes/220818/Solution_5653_줄기세포배양.java
- jes/220818/Solution_D4_1227_미로_2.java
- jes/220818/Solution_D4_2819_격자판의숫자이어붙이기.java
`다음주가 무섭다ㅠ`
- 조건
- 주어진 문자열 S의 문자를 재배치하여 인접한 문자가 다른 문자가 되는 경우의 수 구하기
- 1시간 반
- 막힌 부분
처음에는 조건에 따라 처리 했는데 뭔가 예외가 있는지 테케는 다 돌아가는데 안되길래… 그냥 if else if else 조건 다 빼고 돌리니까 되더라는
- 문자열을 문자로 쪼개서 int 배열에 a=0, b=1, … z=25 문자를 숫자로 넣음
-  Next Permutation 사용하여 중복 없이 순열을 구한 다음 생성된 배열에서 인접한 문자가 같은 문자인지 확인해줌
- 인접한 문자가 모두 다른 문자인 경우 res++
- 순열!
- 조건
- 0: 길 / 1: 벽 / 2: 시작점 / 3: 끝점
- 미로 크기는 100 x 100
- 미로 통과 가능하면 1, 아니면 0
- 30분
- 풀이
- 끝점에서부터 Queue로 BFS 알고리즘 통해 풀이
- 이미 갔던 길은 isChecked[][] 배열로 처리
- 그냥 미로다
- 조건
- 4 x 4 격자판에 0~9까지 숫자 주어짐
- 각 위치에서 상하좌우로만 이동 가능하고 총 6번 이동했을 때 숫자 하나 완성
- 주어진 격자판에서 최종적으로 겹치지 않는 몇개의 숫자가 완성될 수 있는지 찾는 문제!
- 1시간
- 입력이 작아서 DFS로 구현
- 입력을 String으로 받아서 DFS할 때 문자열로 이어붙일 수 있도록 함
- for문을 통해 격자판의 한칸마다 DFS 수행
- 총 6번 이동했을 때마다 HashSet에 문자열을 추가하여 중복 제거하고 HashSet의 크기를 출력
-  StringBuilder 사용했는데 마지막에 \n …
> [220818] 조은서

- syj/220818/BOJ_1342_행운의문자열.java
- syj/220818/SWEA_1227_미로2.java
- syj/220818/SWEA_2117_홈방범서비스.java
- syj/220818/SWEA_2819_격자판의숫자이어붙이기.java
- syj/220818/SWEA_5653_줄기세포배양.java
`이대로만 가자 ~~~~~~`
_메모리 : 89,884 kb       
실행시간 : 2,229 ms_
BFS + 방문체크
메모리 & 시간관리 잘하기
3시간
1. 최대 크기 배열 생성
2. 맵 모든 칸 -2로 초기화
3. 초기 세포를 map 가운데 배치하고 배양 시작
4. 세포를 배양할 때는 카피맵 사용 (원래 세포의 생명력 보관)
5. 완탐을 통해 활성 상태인 곳에서 배양함수 불러오기
6. 세포배양 후 새로 배양 된 곳은 원본 맵에 추가
7. 세포 배양한 후에는 초기 생명력 부여
8. 배양 후에는 비활성상태인 곳 -1 해주기
배열 크기 ..
배양 후에 바로 죽이면 안되고 원래의 생명력 동안 지속한 후 죽여야 함
BFS로 나중에 다시 풀어보기 !!!
메모리 : 11920 kb	
실행시간 : 304 ms
순열 (비트마스킹)
3일
순열 (비트마스킹)
1. 인접한 문자와 같은 문자일 경우 x
2. 중복 제거 >>> i번째 자리에 같은 알파벳이 등장하면 패쓰 ----> 비트마스킹
3. 알파벳에 따라 위치를 저장해야 하니까 char 사용!!!
백트레킹 && 비트마스킹을 통해 중복제거
_메모리 : 23964 kb	
실행시간 : 121 ms_
재귀 + 방문체크
40분
1. 시작위치 저장
2. 시작위치 방문체크
3. 미로 찾기 시작
4. 4방탐색으로 유효한 곳으로 이동
5. 도착했을 경우 true반환
6. 결과 출력
4방탐색 + 방문체크 도착할 때까지 유지
_메모리 : 63816 kb	
실행시간 : 208 ms_
완탐 문제 + 중복 방지 위해 HashSet 사용
40분
1. 모든 위치에서 7글자 만드는 모든 경우의 수 …
> [220818] 서예지

- ytj/220901/SWEA_1952_SwimmingPool.java
- ytj/220901/SWEA_2115_HoneyHarvesting.java
`아무리 쉬워보이는 문제라도 설계를 최대한 견고하고 짜임새 있게 만들고 구현을 하도록 하자! `
`또한, 구현의 실수를 줄일 수 있게 중간 중간 기능들을 반드시 테스트 한 뒤, 다음 단계로 진행하도록 하자!`
`이 문제는 1월 부터 12월 까지의 수영장 이용 계획이 주어졌을 때, 1일, 1달, 3달, 1년 이용권을 사용하여 수영장을 이용할 수 있는 방법들 중 요금이 가장 작은 경우의 비용을 구하는 것이다.`
ex ) 12월 이용 계획
ex ) 이용권 금액 
`1일 : 10 원`   `1달 : 40 원`   `3달 : 100 원`   `1년 : 300 원 `
- `52m`
- dfs를 사용하여 매개변수로 '현재 월' 과 '현재 비용'을 넘겨준다. 
- 기저 조건으로
`1. '현재 월'이 12월 보다 크거나 같을 때`
`2. '현재 까지 비용'을 비교하여 최소 값을 저장한다.`
`return`
- 수행 조건으로
`1. '현재 월' 에서 이용 계획이 0일 일 때, '현재 월 + 1' 과 '현재 비용' 을 넘겨준다. `
`2. 이용 계획이 존재 하면`
`- 1일 이용권으로 사용`   `dfs( '현재 월 + 1' , '현재 비용 + 현재 월의 이용계획 x 1일 이용권 비용' ) 재귀 호출.`
`- 1달 이용권으로 사용`   `dfs( '현재 월 + 1' , '현재 비용 + 1달 이용권 비용' ) `
`- 3달 이용권으로 사용`   `dfs( '현재 월 + 3' , '현재 비용 + 3달 이용권 비용' ) `
- dfs 진행 완료 후, 현재 까지의 최소 비용과 1년 이용권 요금을 비교하여 더 적은 값을 최종 답으로 …
> [220901] 윤태준

- ahg/220901/Honey_Harvesting.java
- ahg/220901/Swimming_Pool.java
오랜만에 문제를 풀었더니 어색한 느낌
1일 이용권 , 1달 이용권 , 3달이용권 ,1년 이용권이 있다
달의 이용권은 항상 해당 달 1일부터 시작한다.
단, 최대 값이 12이기 때문에 3달이용권이 11 이상에서 써질 경우 12까지만 적용되고 나머지 달 수는 버려진다.
1년동안 정해진 일 수가 주어 질 때 가장 적은 비용으로 다닐 수 있는 경우의 수를 구하라
30분(설계 10분, 코딩 5분, 디버깅 + 수정 15분)
- 요약 : 부분집합을 통한 최소값 도출(
1. 1일, 1달, 3달, 1년 가격을 저장할 배열 생성
2. 월별 수영장을 가는 횟수를 저장할 배열 생성
3. 초기 최소값을 1년 비용으로 설정
4. 1년을 제외한 1일,1달,3달을 대상으로 부분집합을 시행
- 1년은 12달이고 모든 달에 수영장을 이용하는 횟수가 있는것이 나올 수 있는 최대 경우의 수
탈출조건
1. 12개월치의 계산이 끝날 경우
2. 현재 경우의 수가 이미 현재 최소값보다 커질경우
또한, 현재 달에 수영장을 이용하는 날이 없는경우(0)엔 갈래를 나누지 말고 바로 다음달로 이동
시간 복잡도
- O(3^N)
- 즉, 최대 경우의 수는 3^12 = 531,441번
1. 1일 이용권은 반드시 그 달을 전부 적용 시켜 줘야한다.
6. 3달 이용권은 11월 이상에서 쓰면 12 이상 달은 사라진다
7. 1년 이용권은 경우의 수가 반드시 1개밖에 존재 할 수 없기 때문에 max_value의 초기값을 1년 이용권의 값을 잡아준다
- 최대 한 축의 길이(N)가 10인 벌통맵이 주어짐
- 이 벌통맵 에 2명의 양봉업자가 꿀을 채취
- 양봉업자 둘은 일정 …
> [220901] 안효관

- jes/220901/Solution_1952_수영장.java
- jes/220901/Solution_2115_벌꿀채취.java
`오랜만에 푼 기분 ^_^ 확실히 적으면서 하니까 실수가 줄어드는것 같다`
- 이용권 종류
1. 1일 이용권 : 1일 이용 가능
2. 1달 이용권 : 1달 이용 가능. 매달 1일부터 시작
3. 3달 이용권 : 연속된 3달 이용 가능. 매달 1일부터 시작. 다음 해와 연속해서 사용 불가 ex) 11, 12, 1 / 12, 1, 2 -> X
4. 1년 이용권 : 1년 이용 가능. 매년 1월 1일 시작 -> 구매 시 다른 이용권 필요 없음
목표: 4가지 이용권을 적절히 구매하여 가장 적은 비용 찾기
-> 완전 탐색
-  35분
모든 경우의 수 탐색 -> DFS 
시간 단축 -> 가지치기(최소 비용을 넘겼을 때)
처음에 1년 이용권 비용을 최소 비용으로 설정하고 1일 이용권부터 순서대로 DFS로 최소 비용 갱신하기
```java
최소비용 = 1년권 비용으로 설정 후 dfs
dfs(누적 비용, 몇번째 달인지){
if( 누적비용 > 최소 비용 ) return
if( 12월이면 ) 최소 비용 갱신 후 return
dfs(1일권 비용*계획일수, 달+1)
dfs(1달권 비용, 달+1)
if( 11월 전까지 ) dfs(3달권 비용, 달+3)
}
```
DFS + 가지치기
- 조건
1. 일꾼 2명이 겹치지 않게 가로로 연속되는 M개 벌통 선택
2. 각각 선택한 벌통에서 꿀 채취. 이때, 1개의 벌통은 1개의 용기에 담을 수 있고 일부만 담기 불가능
3. 최대로 채취할 수 있는 양 C를 넘게 채취할 수 없음
4. 각 용기에 있는 꿀의 양의 제곱을 합한 값 = 수익
목표: 두 일꾼이 자리 겹치지 않고 C를 넘지 않게 벌꿀 채취하여 …
> [220901] 조은서

- jes/220908/Solution_5656_벽돌깨기.java
- jes/220908/Solution_5658_보물상자비밀번호.java
------------------------------------
`나도 빨리풀고싶당`
* 조건
1. 각 변에 16진수 숫자(0~F)가 있고 한 번 돌릴때마다 시계방향으로 한칸씩 회전함
2. 각 변에는 동일한 개수의 숫자가 있고 시계방향 순으로 높은 자리 숫자에 해당하며 하나의 수를 나타냄
3. 회전하면서 동일한 수가 중복 생성되는 것 카운트 제외
* 목표: 주어진 수로 만들 수 있는 수 중 K번째로 큰 수를 10진수로 표현
- 풀이 시작 시간: 22.09.14 22:30
- 풀이 종료 시간: 22.09.14 23:10
- 풀이 시간 : 40분
* 풀이 계획
1. 주어진 숫자 개수만큼 회전하여 숫자 생성(중복 제외)
2. 내림차순 정렬
3. K번째로 큰 수 출력
- Treeset : 중복 제거 및 정렬
- 16진수인 상태에서 treeset에 넣어도 되는것 같다! 굳이 작업 2번 했다는..
* 조건
1. 구슬은 좌, 우로만 이동 가능 -> 항상 맨 위에 있는 벽돌만 깨뜨릴 수 O
2. (벽돌에 적힌 숫자 -1) 칸 만큼 상하좌우로 같이 제거
3. 이 때 제거되는 범위 내 벽돌은 동시 제거
4. 빈 공간 있을 경우 벽돌은 밑으로 떨어짐
5. 구슬 개수 주어짐 : N
* 목표: N개의 구슬 떨어뜨려 최대한 많은 벽돌 제거했을 때 남은 벽돌의 개수 구하기
*	풀이 시작 시간: 22.09.15 20:10
* 	풀이 종료 시간: 22.09.20 01:34
*  풀이 시간 : 50분 + 30분 = 80분
1. 벽돌 정보가 하나라도 1보다 큰 경우 dfs로 모든 경우 탐색 
- 종료조건 -> cnt가 구슬 개수(N)인 …
> [220908] 조은서

- ahg/220908/CrashBrick.java
- ahg/220908/TreasureChestPassword.java
- 한 번 돌릴 때 마다 숫자가 시계방향으로 한 칸씩 회전
- 진수 변환과 정렬이 필요
- 보물상자의 비밀번호가 만들어 지는 경우의 수는 최대 N/4번
- 즉, N/4번을 회전 시키면서 모든 경우의 수를 ArrayList에 저장하고 contains를 써서 검사 (16진수로 변환해서 TreeSet에 저장했어도 좋았을듯)
- 꺼낸 애들을 전부 10진수로 변환해서 정렬 한 후 결과값 도출
30분~1시간
1. N/4번 반복문 설정
2. 반복문 내에서  N/4 의 갯수로 자른 값을 저장
3. 저장이 끝났다면 회전
4. 반복문이 끝나면 2진수 변환 후 정렬
5. K번쨰 값을 찾아서 출력
- 최대 연산횟수는 N/4 * N = 28/7 * 28 =112번
- Collections.sort의 시간복잡도(O(nlog(n)))
- 배열을 움직이지 않을거라면 시작지점을 계속 옮겨주면서 탐색해주기
- 어떠한 경우에도 N/4가 최대로 움직이는 값이 된다
- 벽돌이 떨어지면 닿는 위치는 반드시 가장 위쪽
- 스플래쉬가 계속해서 일어날 수 있음
- 구슬은 중복된 위치에 떨어질 수 있고 최대 4개까지 떨어질 수 있음 ( 중복순열 )
- 벽돌이 부딪힌 위치에서 BFS
30분 ~ 1시간
1. 벽돌의 x,y위치와 스플래쉬 범위를 담을 클래스를 생성하고 초기데이터 저장
2. 구슬이 떨어질 수 있는 횟수만큼 중복 순열을 돌림
3. 중복순열 경우의수를 도출하면 초기데이터로 받은 맵을 복사한 맵2와 BFS 탐색
4.  BFS로 구슬이 떨어졌을때 부서질 벽돌을 모두 체크
5.  복사한 맵을 전부 탐색하면서 체크한 부서질 벽돌을 전부 삭제
6.  복사한 …
> [220908] 안효관

- jes/220915/Solution_2105_디저트카페.java
- jes/220915/Solution_4008_숫자만들기.java
`A형 이렇게 나오면 좋겠다.`
*	조건
1. 대각선 방향으로 이동 -> 사각형 만들어야 함
2. 같은 숫자(같은 종류의 디저트)는 만날 수 없음
3. 2종류 이상의 디저트를 먹어야 함
4. 왔던 곳은 되돌아 갈 수 없음
* 	목표: 디저트를 가장 많이 먹을 때 디저트 개수 구하기
* 풀이 시작 시간: 22.09.20 23:00
* 풀이 종료 시간: 22.09.21 00:41
* 풀이 시간 : 설계 10분 + 코딩 30분 + 디버깅 30분 => 약 70분
* 	풀이 계획
1. 사각형을 만들기 위해 양옆 각 1줄, 아래 2줄을 제외한 부분에서 탐색
2. dfs 통해 사각형이 만들어 질 수 있는지 탐색
이 때, 종료 조건은 4방향을 모두 돌고나서 도착한 좌표가 시작점인 경우
3. 최대값(디저트 가게 방문 횟수) 갱신이 된 경우 최대값, 안된 경우 -1 출력
DFS
*	조건
1. N개의 숫자 적혀있는 게임판에서 +, -, x, / 연산자 카드 사용
2. 연산자의 우선순위 고려 X 왼쪽부터 오른쪽으로 차례대로 계산
* 	목표: 수식 계산했을 때 결과가 최대인 수식의 값 - 최소인 수식의 값 구하기
* 풀이 시작 시간: 22.09.21 23:10
* 풀이 종료 시간: 22.09.22 00:30
* 풀이 시간 : 설계 10분 + 코딩 30분 + 시간초과 수정 15분 = 약 1시간
* 	풀이 계획
1. 순열 -> 시간초과 ^__^
2. Next Permutation -> 시간 초과 해결
*  풀이 방법
1. 각 연산자 +, -, *, / 를 0, 1, 2, 3으로 표현하여 배열 생성
2. 연산자 배열을 Next …
> [220915] 조은서

- ahg/220915/DessertCafe.java
- ahg/220915/MakeNumber.java
기본적인 것들을 복습하는 문제들
- 메모리 93,652kb
- 실행시간 167ms
- 같은 숫자로는 갈 수 없음
- 대각선으로만 움직일 수 있음
- 같은 자리에서 움직이기 불가능
- 갔던 길을 갈 수 없음
- 디저트를 먹을 수 없는 경우의 수가 존재
- 디저트를 가장 많이 먹을 때의 디저트 수
- 20분
1.  2차원 배열에 정보를 입력받음
2.  가로 1부터  N-1미만 까지 , 세로 0부터 <N-2 미만 까지 2중for문 탐색하면서 오른쪽 대각선 아래칸 부터 dfs
3.  매 칸마다 선을 꺾은 경우의 수를 탐색하고, 범위밖을 벗어날 경우 선 꺾기
4.  선이 4번 이상 꺾이고 탐색 하면서 현재x,y가 시작 x,y에 도달할 경우 결과 값 갱신
5. 2중for문 끝나면 결과값 출력
- 대각선 사각형이 완성되야 하기 때문에 좌,우로는 반드시 한칸의 여유가 있어야하고 아래쪽으로 -2칸의 여유가 있어야 한다.
- 메모리 49,540 kb
- 실행시간 144ms
- 숫자를 받고
- 각 사칙연산자의 갯수를 받고
-  숫자들을 주어진 사칙연산자 갯수를 써서 연산 후 최대값 - 최소값을 구한 후 출력
- 15분
1. 각 연산자의 갯수를 길이 4의 배열에 저장하고
2. 각 ,연산자의 남아있는 갯수가 0이 아닐경우 지금까지의 연산 결과와 다음 숫자와 해당 연산자를 사용하여 연산한 결과를 저장하면서 dfs탐색
3. 숫자 길이만큼 탐색 다 끝나면 최소값과 최대값 갱신
4. 모든 경우의수 탐색이 끝나면 최대값-최소값 연산 결과를 출력
- 경우의 수당 total값을 첫번쨰 숫자로 설정해주고 탐색할 숫자배열의 Index를 두번쨰부터 …
> [220915] 안효관

- yhg/220915/SWEA_2105_디저트카페.java
- yhg/220915/SWEA_4008_숫자만들기.java
- 메모리 : 115,684 kb -> 32,592 kb
- 실행시간 : 1,233 ms -> 200 ms
백트래킹
생각해보니 배열을 들고다닐 필요 없이 바꿔놓고 다시 되돌려 놓으면 됐었다. 
30분
```
1. 방문을 처리할 visited배열 , 4가지 대각선 방향배열 , 디저트의 종류를 확인할 배열을 선언
2. 각 방향의 진행정도에서 가지치기 진행
- 기저조건
1. 만약 4번을 꺾었다 -> 사각형이 될수 없음
2. 만약 이미 방문했던 곳이라면? 
2-1. 처음 시작한곳으로 돌아왔다 -> 3번만 꺾었는지 체크 -> 사각형 조건 완성 -> 디저트 종류개수 결과  저장
2-1. 처음 시작한 곳이 아니다 -> return
3. 이미 디저트가 중복되었다
3.  각 가지치기를 들어갔다 나오면서 방문처리와 디저트 체크 처리를 해제한다. 
```
가로나 세로의 길이가 0인 사각형의 체크가 필요하다. 
- 메모리 : 26,672 kb
- 실행시간 : 시간 : 125 ms
[dfs]
1번의 문제풀이 방식과 거의 유사하지만 일단 모든 숫자를 사용해야 하기 때문에 DFS
30분
```
1. 각각의 숫자를 순서대로 진행하면서 연산을 하나씩 진행한다. 
2.연산을 진행하는 조건은 'visited에 있는 숫자가 연산자보다 작다 == 연산자를 사용할 수 있다' 이다.
3. 각각의 연산에 대하여 visited를 다시 되돌려놓고 다음 연산자를 진행한다. 
4. 만약 index가 끝까지 진행되었다면 max과 min을 초기화 한다. 
```
기본적으로 순열로 생각할 수 있지만 이제는 순열이 생각나면 안된다는 마음으로 풀려고한다. …
> [220915] 유현근

- ahg/220929/BuildAirStrip.java
- ahg/220929/CarRepairShop.java
약간 집중력 저하가 오는 시기
- 고객이 이용했던 접수 창구번호와 장비 창구번호가 존재
- N개의 접수창구와 M개의 장비창구가 있다
- i에서 고객 한명의 고장을 접수하는데 걸리는 시간은 ai
- j에서 고객 한명의 고장을 접수하는데 걸리는 시간은 bj
- 지금까지 방문한 고객은 K명, 도착하는대로 번호 받음
- 고객번호 k 고객이 차량 정비소에 도착하는 시간은 tk
- 정비소에 도착하면 빈접수창고에 가서 접수
- 빈 접수창고가 없으면 대기
- 접수창구의 우선순위 1. 여러명 기다리면 고객번호가 낮은 순서,빈 창구가 여러곳이면 창구번호가 낮은 순
- 정비창구의 우선순위 1, 먼저 기다리는 고객 우선,동시에 접수하고 정비창구에 이동하면 창구번호가 작은 고객이 우선,빈 창구가 여러 곳이면
- 창구번호가 작은곳부터
- 없을경우 -1
- 1시간
1.접수창구 대기열,정비창구 대기열 큐를 생성
2.반복 or 재귀를 돌리면서 고객이 왔을 경우 접수창구 배열에 넣기
3.시간이 될때마다 오는 고객들을 큐에 넣어줌
4.고객이 들어간 순간부터 시간초를 재서 ai초에 도달하면 탈출후 정비창구 큐에 넣기
5.정비창구도 접수창고와 비슷한 로직을 사용하는데 순차적 탐색을 해서 접수창구가 작은 순서 먼저 큐에 넣어주는 식으로 해결
N -> 접수창구 갯수, M -> 정비창구 갯수, K -> 차량정비소를 방문한 고객의 수
A -> 지갑 두고간 손님이 방문한 접수창고,B -> 지갑 두고간 손님이 방문한 정비창고
a1 -> 접수창고의 처리시간 , b1 -> 정비창구의 처리시간 tk -> k번쨰 고객이 차량 정비소를 방문하는 시간
- 문제를 …
> [220929] 안효관

- syj/221006/SWEA_1949_등산로조성.java
- syj/221006/SWEA_2112_보호필름.java
- syj/221006/SWEA_2382_미생물격리.java
- syj/221006/SWEA_2383_점심식사시간.java
- syj/221006/SWEA_5650_핀볼게임.java
`내일 시험 다들 화이팅 💪`
_메모리 : 31,732kb       
실행시간 : 130ms_
`중복순열` + `빡구현`
사람마다 계단을 중복순열로 정해서
내려보내자 !!!
2일 (현근오빠가 찾아준 반례를 다행히 기존 코드를 재사용해서 고쳤다 ...)
```
1. 사람 객체 (계단까지 거리, 계단 번호, 계단 길이, 기다림 여부)
2. 계단 위치 2개 저장
3. 사람마다 계단 정하기 (중복순열 0 or 1)
4. 계단 내려보내기
- 먼저 내려가는 중인 사람 계단 길이 1씩 줄이기
- 계단 길이가 0인 사람(다 내려온 사람) 카운트에서 빼주기
- 이제 막 도착한 사람 1분 대기
- 이미 기다리고 있던 사람은 바로 내려보내기
- 계단 꽉 차서 기다려야 되는 사람 기다림 여부 체크해주기
```
처음에 로직 짤 때 꼼꼼히 검토하기 ! ! !
_메모리 : 67,964kb
실행시간 : 444ms_
`단순구현`
문제에 나온 대로 구현만 하면 문제 없을 것 같다.
20 - 30분
```
1. 군집 객체 생성 후 배열에 담기 (군집 객체 내용 : r, c, 미생물 수, 방향)
2. M시간 동안 다음 구간 반복
- 미생물 전체 이동 (0 || N - 1 에 닿은 경우 방향 바꾸고 (미생물 수/2))
- 미생물 병합 (미리 좌표 -> 좌표가 같은 경우 미생물 수를 기준으로 내림차순 정렬해 놓기)
3. M시간 후 미생물 합 출력
```
정렬을 미리 하면 쓸데없는 연산을 줄일 수 있다.
_메모리 : 27,432kb
실행시간 : 104ms_
`dfs` + `완전탐색`
문제 설명이 살짝 이상한데
낮은 곳으로만 등산로를 이어갈 수 …
> [221006] 서예지

- ahg/221006/LunchTime.java
- ahg/221006/MakeHikingTrail.java
- ahg/221006/MicrobialIsolation.java
- ahg/221006/PinballGame.java
- ahg/221006/ProtectFilm.java
아직까지 인덱스가 이동할 정확한 위치를 햇갈려한다.
- 부분집합 + 맨허튼 거리공식을 이용한 구현 문제
1시간
1. 초기값을 입력받을때 사람정보와 계단정보의 리스트,배열을 만들어서 저장
2. 부분집합으로 첫번째 계단을 내려갈 사람과 두번째 계단을 내려갈 사람을 나눔
3. 맨허튼 거리값 공식을 이용하여 시간마다 계단을 갈 수 있는 사람들을 체크해 계단 depth만큼의 값을 주고 이동시킴
4. 이동 후엔 계단마다 최대 3명까지 depth를 1씩 빼줌
5.  depth가 0이되면 그 요소를 삭제후 반복
6. 각 계단에 대기중인 사람,갈 사람이 없을 경우 최소값 갱신 후 종료
7. 모든 부분집합이 끝나면 최소값 출력
- 계단에 간 사람들은 결국 다 내려가야 하기때문에 굳이 각각의 사람들을 따로 계산하기 보단 누구든 최대 3명까지 1씩 깎아주기
- 단순 구현 문제
1시간 15분
1. 미생물의 위치,수,방향을 클래스로 만들어 리스트에 저장
2. 같은 위치에 3개이상 겹칠경우 방향을 정하기 위해 int형 2차원 배열 생성, 합쳐진 값과 미생물의 정보를 저장하기 위해 미생물 클래스의 2차원배열 생성
3. 리스트를 반복하며 미생물들을 각 방향으로 이동시키면서 방향을 정하기위한 배열과,미생물의 정보를 저장하기 위한 배열을 갱신
4. 모든 미생물의 이동 및 병합이 끝났다면 미생물 군집 수 만큼 반복을 돌리며 약품 라인에 있는지 체크
5. 약품 라인에 있을 경우 미생물의 수/2 를 해주고 방향을 반대방향으로 전환
6. 2~5를 시간을 +1 해주며 반복하고 시간이 격리시간이상이 될 경우 미생물리스트를 반복돌려 값을 전부 더해주고 …
> [221006] 안효관

- jes/221006/Solution_1949_등산로조성.java
- jes/221006/Solution_2112_보호필름.java
- jes/221006/Solution_2382_미생물격리.java
- jes/221006/Solution_2383_점심식사시간.java
- jes/221006/Solution_5650_핀볼게임.java
------------------------------------
`디버깅 너무 어렵다`
// 32784kb 128ms
*  목표: 모든 사람이 계단을 다 내려가는데 걸린 최소 시간
*  조건
1. N*N 크기의 정사각형 모양의 방
2.  P: 사람 / S: 계단 입구
3. 계단 입구까지 이동 시간 = |PR - SR| + |PC - SC|
PR, PC: 사람 세로, 가로 위치 / SR, SC: 계단 입구 세로, 가로 위치
4. 계단 내려가는 시간
4-1. 계단 입구 도착하고 1분 후(이동 시간+1) 아래칸으로 내려갈 수 있음
4-2. 계단을 동시에 내려가는 사람은 최대 3명
4-3. 이미 계단을 3명이 내려가고 있으면 그 중 한명이 이동 완료할때까지 대기
4-4. 계단 길이 K일 때 계단을 완전히 내려가는 시간은 K분 => 최종적으로 계단 입구 도착 후 K+1분
*	풀이 시작 시간: 22.10.09 20:00
* 	풀이 종료 시간: 22.10.09 21:43
*  풀이 시간 : 설계 10분 + 코딩 30분 + 디버깅 40분 = 80분
1. 각 사람이 어떤 계단을 이용할지 부분집합으로 나누기(subset())
2. 계단 입구까지 이동 시간 계산하여 오름차순 정렬(Collections.sort() + Comparable) 
3. 먼저 입구에 도착한 사람부터 계단 내려가기(arriveTime())
3-1. 처음 3명은 무조건 계단 내려갈 수 있으므로 이동 완료시간 계산
3-2. 앞 사람이 이동완료한 시간보다 계단 입구에서 내려가려는 시간이 더 늦을 때(나중일때) 이동 완료시간 계산
3-3. 이미 계단에 내려가고 …
> [221006] 조은서

- ytj/221006/SWEA_1949_HikingTrail.java
- ytj/221006/SWEA_2112_ProtectiveFilm.java
- ytj/221006/SWEA_2382_Microbe.java
- ytj/221006/SWEA_2477_LunchTime.java
- ytj/221006/SWEA_5650_Pinball.java
`주말 마다 문제를 최대한 풀려고 노력 중,  근데 그럼 언제 쉬지?`
이 문제는 이전에 풀었던 정비소 문제처럼 시간 흐름에 따른 시뮬레이션 구현문제 이다.
`1. 사람들과 계단의 위치, 계단을 내려가는데 걸리는 시간 주어지고 각 계단은 다 내려가는데 특정한 시간이 소요된다.`
`2. 계단에 3명 이상 내려가고 있다면 1명이라도 완료된 후 내려갈 수 있다.`
`3. 또한 계단 위치에 도착 후, 1분이 지나야 계단을 내려갈 수 있다.`
`4. 이때, 모든 사람들이 계단을 내려가 이동이 완료되는 시간이 최소가 되는 경우를 찾고, 그 때의 시간을 구해야 한다.`
- `2h 8m`
`1. 주어지는 입력 값으로 계단은 항상 2개 이며, 인원은 최대 10명이므로 입력 값이 작다. 따라서, `
`2. 현근이가 이전에 정비소 문제에서 한 것처럼, 1초 단위로 움직임을 구현하지 않고, 앞에 계단에 배치된 인원에 따라 뒤에 올 사람의 계단 진입 시간을 결정하게 한다.`
`3. 부분집합을 통해 1,2번 계단을 결정하고 결정된 케이스마다 가장 늦게 계단을 탈출한 인원의 시간을 저장해서 모든 케이스 중 가장 빠른 마지막 인원의 시간을 도출한다.`
> 이 문제의 포인트는 다른 시뮬레이션 문제와 마찬가지로 구현할 기능이 내가 생각한 대로 작동하는지 항상 단일 테스트를 하며, 진행해야 한다.
이 문제는 낚시왕 문제와 매우 유사한 문제이다.
`1. 주어진 조건에 따라 1초 단위로 미생물의 군집 단위로 맵을 이동하며 일정 시간뒤에 남아있는 군집들의 미생물 총 합을 도출하는 문제이다. `
`2. 만약 동일한 위치에 두개 이상의 군집이 …
> [221006] 윤태준
